version: '3.9'
services:
  api_express:
    container_name: api
    image: motorshop/node:latest
    build: .
    env_file:
      - .env.docker
    ports:
      - 3333:3333
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=api_carshop
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U postgres -d api_carshop',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
