
version: "3.9"
services:
  api_express: 
    container_name: db
    image: node:16-alpine
    build: .
    ports:
      - 3333:3333
    depends_on: 
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
        